import sqlite3

def data():

    connection_obj = sqlite3.connect('assets/data.db')
    
    # cursor object
    cursor_obj = connection_obj.cursor()

    cursor_obj.execute("DROP TABLE IF EXISTS [cooltable]")
    cursor_obj.execute("DROP TABLE IF EXISTS [fish]")
    
    
    # Creating table
    table = """ CREATE TABLE [cooltable] (
    [People] TEXT,
    [Amaranth] TEXT,
    [Amethyst] TEXT,
    [Aquamarine] TEXT,
    [Artichoke Dip] TEXT,
    [Autumn's Bounty] TEXT,
    [Baked Fish] TEXT,
    [Banana Pudding] TEXT,
    [Battery Pack] TEXT,
    [Bean Hotpot] TEXT,
    [Beer] TEXT,
    [Beet] TEXT,
    [Blackberry Cobbler] TEXT,
    [Blueberry] TEXT,
    [Blueberry Tart] TEXT,
    [Cactus Fruit] TEXT,
    [Carp Surprise] TEXT,
    [Catfish] TEXT,
    [Cauliflower] TEXT,
    [Cave Carrot] TEXT,
    [Chanterelle] TEXT,
    [Cheese Cauliflower] TEXT,
    [Chocolate Cake] TEXT,
    [Chowder] TEXT,
    [Clay] TEXT,
    [Cloth] TEXT,
    [Coconut] TEXT,
    [Coffee] TEXT,
    [Common Mushroom] TEXT,
    [Complete Breakfast] TEXT,
    [Copper Bar] TEXT,
    [Crab Cakes] TEXT,
    [Cranberry Candy] TEXT,
    [Crispy Bass] TEXT,
    [Crocus] TEXT,
    [Daffodil] TEXT,
    [Dandelion] TEXT,
    [Diamond] TEXT,
    [Dish O' The Sea] TEXT,
    [Dragon Tooth] TEXT,
    [Driftwood] TEXT,
    [Duck Egg] TEXT,
    [Duck Feather] TEXT,
    [Eggplant Parmesan] TEXT,
    [Emerald] TEXT,
    [Escargot] TEXT,
    [Fairy Rose] TEXT,
    [Farmer's Lunch] TEXT,
    [Fiddlehead Risotto] TEXT,
    [Fish Stew] TEXT,
    [Fish Taco] TEXT,
    [Flounder] TEXT,
    [Fried Calamari] TEXT,
    [Fried Eel] TEXT,
    [Fried Mushroom] TEXT,
    [Frozen Tear] TEXT,
    [Fruit Salad] TEXT,
    [Ginger] TEXT,
    [Ginger Ale] TEXT,
    [Glazed Yams] TEXT,
    [Goat Cheese] TEXT,
    [Goat Milk] TEXT,
    [Gold Bar] TEXT,
    [Grape] TEXT,
    [Green Tea] TEXT,
    [Hazelnut] TEXT,
    [Holly] TEXT,
    [Hot Pepper] TEXT,
    [Ice Cream] TEXT,
    [Iridium Bar] TEXT,
    [Jade] TEXT,
    [Jelly] TEXT,
    [Joja Cola] TEXT,
    [Large Goat Milk] TEXT,
    [Leek] TEXT,
    [Lemon Stone] TEXT,
    [Lingcod] TEXT,
    [Lobster] TEXT,
    [Lobster Bisque] TEXT,
    [Magma Cap] TEXT,
    [Mango] TEXT,
    [Mango Sticky Rice] TEXT,
    [Maple Bar] TEXT,
    [Mead] TEXT,
    [Melon] TEXT,
    [Miner's Treat] TEXT,
    [Morel] TEXT,
    [Nautilus Shell] TEXT,
    [Oak Resin] TEXT,
    [Obsidian] TEXT,
    [Octopus] TEXT,
    [Omni Geode] TEXT,
    [Orange] TEXT,
    [Ostrich Egg] TEXT,
    [Pale Ale] TEXT,
    [Pancakes] TEXT,
    [Parsnip Soup] TEXT,
    [Peach] TEXT,
    [Pepper Poppers] TEXT,
    [Pickles] TEXT,
    [Piña Colada] TEXT,
    [Pine Tar] TEXT,
    [Pink Cake] TEXT,
    [Pizza] TEXT,
    [Plum Pudding] TEXT,
    [Poi] TEXT,
    [Pomegranate] TEXT,
    [Poppy] TEXT,
    [Poppyseed Muffin] TEXT,
    [Pufferfish] TEXT,
    [Pumpkin] TEXT,
    [Pumpkin Pie] TEXT,
    [Pumpkin Soup] TEXT,
    [Purple Mushroom] TEXT,
    [Quartz] TEXT,
    [Radioactive Bar] TEXT,
    [Radioactive Ore] TEXT,
    [Rainbow Shell] TEXT,
    [Red Plate] TEXT,
    [Rhubarb Pie] TEXT,
    [Rice Pudding] TEXT,
    [Roasted Hazelnuts] TEXT,
    [Roots Platter] TEXT,
    [Ruby] TEXT,
    [Salad] TEXT,
    [Salmon Dinner] TEXT,
    [Sandfish] TEXT,
    [Sashimi] TEXT,
    [Sea Cucumber] TEXT,
    [Sea Urchin] TEXT,
    [Seafoam Pudding] TEXT,
    [Snail] TEXT,
    [Snow Yam] TEXT,
    [Solar Essence] TEXT,
    [Spaghetti] TEXT,
    [Spice Berry] TEXT,
    [Spicy Eel] TEXT,
    [Squid] TEXT,
    [Squid Ink] TEXT,
    [Stir Fry] TEXT,
    [Strawberry] TEXT,
    [Stuffing] TEXT,
    [Sturgeon] TEXT,
    [Sugar] TEXT,
    [Summer Spangle] TEXT,
    [Sunflower] TEXT,
    [Super Cucumber] TEXT,
    [Super Meal] TEXT,
    [Survival Burger] TEXT,
    [Sweet Pea] TEXT,
    [Tea Leaves] TEXT,
    [Tiger Trout] TEXT,
    [Tigerseye] TEXT,
    [Tom Kha Soup] TEXT,
    [Topaz] TEXT,
    [Tropical Curry] TEXT NULL,
    [Trout Soup] TEXT,
    [Truffle] TEXT,
    [Truffle Oil] TEXT,
    [Tulip] TEXT,
    [Vegetable Medley] TEXT,
    [Void Egg] TEXT,
    [Void Essence] TEXT,
    [Void Mayonnaise] TEXT,
    [Wild Horseradish] TEXT,
    [Wine] TEXT,
    [Winter Root] TEXT,
    [Wool] TEXT,
    [Yam] TEXT
    );"""

    insert = ["INSERT INTO [cooltable] VALUES ('Abigail','Dislike','Love','Like','Like','Like','Like','Love','Dislike','Like','Like','Dislike','Love','Dislike','Like','Dislike','Like','Dislike','Dislike','Dislike','Neutral','Like','Love','Like','Hate','Like','Dislike','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Neutral','Neutral','Like','Like','Hate','Dislike','Dislike','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Neutral','Dislike','Dislike','Like','Neutral','Hate','Dislike','Like','Dislike','Like','Like','Hate','Neutral','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Dislike','Like','Like','Like','Dislike','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Love','Love','Like','Like','Neutral','Like','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Dislike','Love','Dislike','Neutral','Like','Dislike','Like','Dislike','Dislike','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Dislike');",
    "INSERT INTO [cooltable] VALUES ('Alex','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Neutral','Like','Neutral','Love','Dislike','Like','Like','Like','Like','Neutral','Neutral','Like','Like','Hate','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Neutral','Dislike','Neutral','Like','Neutral','Hate','Neutral','Like','Dislike','Like','Like','Hate','Neutral','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Like','Neutral','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Hate','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Love','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Caroline','Dislike','Like','Like','Love','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Dislike','Like','Like','Like','Dislike','Like','Neutral','Like','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Hate','Dislike','Neutral','Neutral','Like','Like','Like','Like','Like','Love','Like','Love','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Neutral','Love','Dislike','Dislike','Neutral','Like','Dislike','Like','Like','Hate','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Neutral','Like','Like','Like','Neutral','Like','Dislike','Neutral','Dislike','Dislike','Dislike','Love','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Dislike','Hate','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Dislike','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Love','Like','Dislike','Like','Like','Like','Like','Dislike','Dislike','Like','Like','Love','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Clint','Like','Love','Love','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Neutral','Like','Neutral','Like','Like','Like','Like','Like','Dislike','Neutral','Neutral','Like','Like','Hate','Dislike','Neutral','Neutral','Like','Love','Like','Dislike','Like','Love','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Neutral','Love','Neutral','Like','Neutral','Hate','Neutral','Like','Love','Love','Like','Hate','Neutral','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Like','Neutral','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Love','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Dislike','Dislike','Dislike','Like','Like','Dislike','Neutral','Dislike','Dislike','Like','Love','Like','Like','Neutral','Like','Dislike','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Demetrius','Like','Like','Like','Like','Like','Like','Like','Dislike','Love','Like','Like','Like','Like','Like','Like','Like','Neutral','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Neutral','Neutral','Like','Like','Hate','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Neutral','Dislike','Like','Like','Neutral','Hate','Like','Love','Dislike','Like','Like','Hate','Neutral','Neutral','Dislike','Neutral','Neutral','Like','Neutral','Like','Like','Like','Like','Like','Like','Neutral','Neutral','Dislike','Dislike','Neutral','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Neutral','Like','Like','Like','Like','Dislike','Hate','Hate','Neutral','Like','Like','Love','Like','Like','Like','Like','Like','Neutral','Like','Neutral','Hate','Hate','Hate','Neutral','Dislike','Like','Like','Like','Neutral','Neutral','Like','Love','Like','Neutral','Hate','Like','Like','Neutral','Like','Like','Like','Neutral','Neutral','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Neutral','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Dwarf','Like','Love','Love','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Like','Dislike','Like','Like','Like','Dislike','Like','Neutral','Like','Dislike','Like','Dislike','Like','Like','Like','Like','Dislike','Dislike','Like','Like','Hate','Dislike','Dislike','Neutral','Like','Love','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Dislike','Dislike','Neutral','Like','Dislike','Dislike','Neutral','Like','Dislike','Love','Like','Hate','Dislike','Dislike','Love','Dislike','Dislike','Like','Dislike','Neutral','Like','Like','Like','Neutral','Like','Dislike','Neutral','Dislike','Dislike','Dislike','Love','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Dislike','Like','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Love','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Dislike','Neutral','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Love','Like','Like','Neutral','Like','Like','Like','Dislike','Neutral','Hate','Dislike','Like','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Elliott','Hate','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Neutral','Like','Dislike','Dislike','Like','Like','Like','Dislike','Like','Like','Like','Dislike','Like','Dislike','Love','Like','Like','Like','Dislike','Dislike','Like','Like','Hate','Dislike','Neutral','Love','Like','Like','Like','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Dislike','Dislike','Like','Like','Dislike','Dislike','Like','Like','Dislike','Like','Like','Hate','Dislike','Dislike','Dislike','Neutral','Love','Like','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Neutral','Dislike','Dislike','Like','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Like','Like','Love','Hate','Like','Neutral','Like','Like','Like','Dislike','Hate','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Neutral','Like','Hate','Hate','Hate','Hate','Dislike','Dislike','Like','Like','Like','Like','Love','Like','Like','Like','Neutral','Hate','Like','Like','Neutral','Like','Like','Like','Neutral','Neutral','Dislike','Love','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Emily','Like','Love','Love','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Love','Neutral','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Hate','Dislike','Neutral','Neutral','Like','Love','Like','Like','Like','Like','Like','Hate','Dislike','Like','Dislike','Like','Like','Like','Neutral','Like','Like','Like','Neutral','Dislike','Neutral','Like','Neutral','Hate','Neutral','Dislike','Dislike','Love','Like','Hate','Neutral','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Like','Neutral','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Like','Hate','Hate','Neutral','Like','Like','Dislike','Like','Like','Love','Like','Hate','Dislike','Hate','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Neutral','Dislike','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Dislike','Like','Love','Like','Neutral','Dislike','Dislike','Like','Love','Like','Hate','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Neutral','Like','Neutral','Love','Like');",
    "INSERT INTO [cooltable] VALUES ('Evelyn','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Love','Like','Neutral','Like','Neutral','Like','Hate','Like','Dislike','Neutral','Like','Like','Like','Hate','Like','Neutral','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Love','Like','Hate','Dislike','Neutral','Neutral','Like','Like','Like','Love','Like','Like','Like','Like','Hate','Like','Hate','Like','Like','Like','Neutral','Like','Like','Like','Like','Dislike','Neutral','Like','Neutral','Hate','Neutral','Like','Dislike','Like','Like','Hate','Like','Neutral','Dislike','Hate','Hate','Like','Neutral','Neutral','Like','Like','Like','Neutral','Like','Neutral','Neutral','Dislike','Dislike','Hate','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Hate','Like','Like','Like','Neutral','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Hate','Hate','Hate','Hate','Hate','Hate','Neutral','Dislike','Like','Hate','Hate','Hate','Neutral','Like','Neutral','Love','Hate','Hate','Like','Like','Hate','Like','Like','Like','Neutral','Hate','Dislike','Like','Like','Like','Like','Neutral','Like','Love','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('George','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Hate','Like','Neutral','Like','Neutral','Like','Dislike','Like','Like','Like','Dislike','Like','Hate','Like','Like','Hate','Dislike','Neutral','Neutral','Like','Like','Like','Dislike','Like','Like','Like','Like','Dislike','Like','Like','Love','Like','Like','Neutral','Like','Like','Like','Neutral','Dislike','Neutral','Like','Neutral','Hate','Neutral','Like','Dislike','Like','Like','Hate','Neutral','Love','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Like','Neutral','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Hate','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Dislike','Dislike','Dislike','Like','Like','Dislike','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Dislike','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Gus','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Neutral','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Love','Like','Hate','Dislike','Neutral','Neutral','Like','Like','Love','Like','Like','Like','Like','Love','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Neutral','Dislike','Neutral','Like','Neutral','Hate','Neutral','Like','Dislike','Like','Like','Hate','Neutral','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Like','Neutral','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Love','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Hate','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Love','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Haley','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Dislike','Like','Dislike','Like','Dislike','Like','Hate','Dislike','Dislike','Dislike','Like','Like','Like','Hate','Like','Love','Like','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Hate','Dislike','Dislike','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Hate','Like','Like','Like','Like','Love','Dislike','Like','Like','Like','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Dislike','Like','Dislike','Like','Like','Hate','Dislike','Dislike','Dislike','Hate','Hate','Like','Dislike','Dislike','Like','Like','Like','Dislike','Like','Dislike','Neutral','Dislike','Dislike','Hate','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Dislike','Love','Like','Like','Like','Like','Hate','Like','Hate','Like','Like','Like','Dislike','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Hate','Like','Hate','Hate','Hate','Hate','Dislike','Dislike','Like','Dislike','Like','Hate','Neutral','Like','Dislike','Like','Hate','Hate','Like','Love','Hate','Like','Like','Like','Neutral','Hate','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Hate','Like','Dislike','Neutral','Dislike');",
    "INSERT INTO [cooltable] VALUES ('Harvey','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Dislike','Like','Dislike','Like','Like','Dislike','Like','Dislike','Like','Like','Love','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Hate','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Dislike','Like','Like','Like','Like','Dislike','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Dislike','Like','Like','Hate','Like','Like','Dislike','Dislike','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Like','Hate','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Dislike','Like','Like','Like','Love','Like','Dislike','Dislike','Dislike','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Like','Like','Hate','Hate','Hate','Like','Dislike','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Like','Dislike','Like','Hate','Like','Dislike','Neutral','Like','Like','Like','Dislike','Hate','Like','Like','Dislike','Love','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Love','Like','Like','Dislike','Dislike','Hate','Like','Love','Like','Neutral','Dislike');",
    "INSERT INTO [cooltable] VALUES ('Jas','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Like','Hate','Dislike','Like','Dislike','Like','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Hate','Hate','Like','Hate','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Hate','Dislike','Dislike','Neutral','Like','Like','Like','Love','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Hate','Neutral','Dislike','Dislike','Hate','Dislike','Dislike','Dislike','Like','Dislike','Like','Like','Hate','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Like','Like','Hate','Dislike','Like','Dislike','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Hate','Like','Like','Like','Like','Hate','Hate','Dislike','Love','Like','Love','Like','Like','Hate','Like','Dislike','Like','Like','Like','Dislike','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Dislike','Dislike','Like','Dislike','Like','Dislike','Neutral','Like','Dislike','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Hate','Like','Like','Dislike','Dislike','Hate','Hate','Hate','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Jodi','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Dislike','Like','Like','Like','Dislike','Like','Like','Like','Dislike','Like','Dislike','Like','Like','Love','Like','Hate','Hate','Love','Like','Hate','Dislike','Like','Neutral','Love','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Love','Like','Like','Like','Dislike','Like','Like','Like','Like','Dislike','Like','Like','Dislike','Dislike','Like','Like','Dislike','Like','Like','Hate','Like','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Love','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Dislike','Dislike','Hate','Hate','Neutral','Like','Love','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Dislike','Dislike','Like','Hate','Like','Dislike','Neutral','Like','Like','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Love','Dislike','Dislike','Hate','Dislike','Like','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Kent','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Hate','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Love','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Hate','Dislike','Like','Like','Neutral','Hate','Like','Like','Dislike','Like','Like','Hate','Hate','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Dislike','Hate','Hate','Neutral','Like','Like','Like','Love','Like','Like','Like','Like','Dislike','Hate','Dislike','Hate','Hate','Hate','Dislike','Dislike','Like','Like','Like','Dislike','Neutral','Like','Like','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Neutral','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Krobus','Like','Like','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Like','Dislike','Neutral','Dislike','Neutral','Dislike','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Love','Dislike','Hate','Dislike','Neutral','Neutral','Dislike','Like','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Neutral','Like','Dislike','Dislike','Neutral','Dislike','Love','Like','Like','Hate','Neutral','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Neutral','Dislike','Dislike','Like','Neutral','Dislike','Dislike','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Dislike','Dislike','Like','Dislike','Like','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Hate','Dislike','Dislike','Love','Dislike','Dislike','Dislike','Like','Hate','Hate','Neutral','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Hate','Like','Hate','Dislike','Dislike','Dislike','Neutral','Dislike','Dislike','Neutral','Dislike','Neutral','Dislike','Dislike','Hate','Like','Like','Dislike','Dislike','Dislike','Like','Neutral','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Neutral','Like','Like','Dislike','Love','Dislike','Love','Love','Like','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Leah','Like','Dislike','Dislike','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Dislike','Dislike','Like','Dislike','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Hate','Like','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Dislike','Like','Like','Like','Like','Love','Like','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Dislike','Like','Hate','Like','Like','Dislike','Dislike','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Like','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Hate','Like','Like','Like','Like','Like','Dislike','Dislike','Hate','Like','Like','Like','Hate','Love','Dislike','Like','Like','Like','Like','Dislike','Hate','Hate','Neutral','Like','Like','Dislike','Like','Like','Dislike','Love','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Like','Dislike','Like','Like','Like','Dislike','Neutral','Love','Like','Like','Dislike','Hate','Like','Like','Dislike','Like','Dislike','Like','Neutral','Dislike','Dislike','Like','Dislike','Like','Like','Love','Like','Like','Love','Hate','Dislike','Hate','Like','Love','Like','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Leo','Like','Like','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Hate','Like','Dislike','Neutral','Dislike','Neutral','Dislike','Neutral','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Like','Dislike','Like','Dislike','Neutral','Love','Dislike','Like','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Neutral','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Dislike','Neutral','Like','Dislike','Hate','Neutral','Dislike','Dislike','Like','Like','Hate','Neutral','Dislike','Dislike','Neutral','Neutral','Dislike','Dislike','Love','Like','Dislike','Hate','Neutral','Dislike','Hate','Like','Dislike','Dislike','Neutral','Dislike','Like','Love','Hate','Dislike','Dislike','Like','Dislike','Dislike','Hate','Dislike','Dislike','Dislike','Dislike','Love','Like','Hate','Dislike','Neutral','Like','Dislike','Dislike','Dislike','Like','Hate','Hate','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Neutral','Dislike','Neutral','Like','Hate','Hate','Dislike','Dislike','Dislike','Like','Dislike','Neutral','Neutral','Dislike','Neutral','Dislike','Neutral','Hate','Like','Like','Neutral','Dislike','Dislike','Like','Neutral','Neutral','Dislike','Dislike','Like','Dislike','Dislike','Neutral','Like','Like','Dislike','Dislike','Dislike','Hate','Dislike','Hate','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Lewis','Like','Like','Like','Like','Love','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Neutral','Neutral','Like','Like','Hate','Dislike','Neutral','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Love','Like','Dislike','Dislike','Neutral','Love','Neutral','Hate','Love','Like','Dislike','Like','Like','Hate','Dislike','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Like','Neutral','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Hate','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Love','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Linus','Like','Dislike','Dislike','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Love','Love','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Dislike','Like','Love','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Love','Hate','Dislike','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Dislike','Like','Hate','Like','Like','Dislike','Neutral','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Like','Neutral','Dislike','Dislike','Neutral','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Neutral','Like','Like','Like','Like','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Dislike','Like','Like','Neutral','Like','Neutral','Hate','Hate','Hate','Like','Dislike','Like','Like','Like','Neutral','Neutral','Like','Like','Like','Neutral','Hate','Like','Like','Neutral','Like','Like','Like','Neutral','Neutral','Dislike','Like','Dislike','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Like','Like','Like','Neutral','Love');",
    "INSERT INTO [cooltable] VALUES ('Marnie','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Hate','Like','Neutral','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Neutral','Neutral','Love','Like','Hate','Dislike','Like','Neutral','Like','Like','Like','Like','Love','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Like','Dislike','Neutral','Like','Neutral','Hate','Neutral','Like','Dislike','Like','Like','Hate','Like','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Like','Neutral','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Love','Like','Like','Like','Like','Hate','Like','Dislike','Like','Love','Like','Neutral','Like','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Maru','Like','Like','Like','Like','Like','Like','Like','Love','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Love','Dislike','Neutral','Love','Like','Like','Dislike','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Like','Neutral','Neutral','Love','Like','Hate','Dislike','Neutral','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Neutral','Love','Neutral','Like','Neutral','Hate','Neutral','Like','Love','Like','Like','Hate','Neutral','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Like','Neutral','Love','Neutral','Neutral','Like','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Like','Love','Hate','Like','Like','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Like','Love','Like','Neutral','Like','Love','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Hate','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Love','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Hate','Like','Like','Like','Dislike','Dislike','Hate','Neutral','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Pam','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Love','Like','Like','Like','Like','Love','Like','Neutral','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Hate','Dislike','Dislike','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Love','Like','Like','Dislike','Like','Like','Neutral','Hate','Like','Like','Dislike','Like','Like','Hate','Like','Neutral','Dislike','Neutral','Neutral','Like','Neutral','Like','Like','Like','Love','Like','Like','Neutral','Neutral','Dislike','Dislike','Hate','Dislike','Like','Dislike','Love','Like','Love','Like','Like','Like','Love','Dislike','Like','Like','Like','Like','Like','Hate','Like','Neutral','Like','Like','Like','Neutral','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Neutral','Like','Neutral','Hate','Hate','Hate','Neutral','Dislike','Like','Like','Like','Hate','Neutral','Like','Like','Like','Neutral','Hate','Like','Like','Neutral','Like','Like','Like','Neutral','Neutral','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Penny','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Hate','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Neutral','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Love','Like','Hate','Dislike','Neutral','Dislike','Like','Love','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Like','Dislike','Hate','Like','Neutral','Hate','Neutral','Like','Dislike','Like','Like','Hate','Like','Like','Dislike','Dislike','Dislike','Like','Neutral','Neutral','Like','Like','Hate','Love','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Hate','Like','Like','Like','Like','Like','Hate','Dislike','Like','Like','Like','Like','Like','Love','Love','Dislike','Like','Like','Like','Neutral','Dislike','Hate','Hate','Neutral','Love','Like','Like','Like','Love','Like','Like','Like','Love','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Love','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Neutral','Hate','Neutral','Dislike','Like');",
    "INSERT INTO [cooltable] VALUES ('Pierre','Like','Dislike','Dislike','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Hate','Like','Dislike','Dislike','Like','Like','Like','Dislike','Like','Neutral','Like','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Hate','Dislike','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Like','Like','Hate','Love','Like','Like','Dislike','Like','Dislike','Like','Like','Like','Like','Dislike','Neutral','Like','Dislike','Dislike','Neutral','Like','Dislike','Dislike','Like','Hate','Like','Dislike','Dislike','Hate','Hate','Like','Dislike','Neutral','Like','Like','Like','Neutral','Like','Dislike','Neutral','Dislike','Dislike','Hate','Dislike','Like','Like','Like','Like','Hate','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Hate','Like','Like','Like','Dislike','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Dislike','Like','Like','Hate','Like','Hate','Hate','Hate','Hate','Dislike','Dislike','Like','Neutral','Like','Hate','Neutral','Like','Neutral','Like','Hate','Hate','Like','Like','Hate','Like','Like','Like','Neutral','Hate','Dislike','Like','Dislike','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Robin','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Like','Dislike','Like','Like','Like','Like','Neutral','Neutral','Like','Like','Hate','Dislike','Neutral','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Love','Like','Dislike','Like','Like','Neutral','Hate','Like','Like','Dislike','Like','Like','Hate','Like','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Love','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Like','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Love','Like','Like','Dislike','Neutral','Like','Like','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Neutral','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Sam','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Dislike','Like','Neutral','Like','Love','Like','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Dislike','Like','Neutral','Like','Dislike','Like','Hate','Like','Like','Like','Like','Dislike','Dislike','Like','Like','Hate','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Hate','Neutral','Like','Dislike','Dislike','Neutral','Like','Hate','Like','Like','Like','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Neutral','Like','Love','Like','Neutral','Like','Dislike','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Love','Like','Like','Like','Hate','Like','Dislike','Dislike','Like','Like','Dislike','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Dislike','Dislike','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Love','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Dislike','Neutral','Dislike');",
    "INSERT INTO [cooltable] VALUES ('Sandy','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Neutral','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Like','Dislike','Like','Like','Like','Love','Love','Neutral','Like','Like','Hate','Dislike','Neutral','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Like','Dislike','Like','Like','Neutral','Hate','Like','Like','Dislike','Like','Like','Hate','Like','Neutral','Dislike','Dislike','Dislike','Like','Neutral','Like','Love','Like','Like','Like','Like','Neutral','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Neutral','Like','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Neutral','Dislike','Like','Like','Like','Dislike','Neutral','Like','Like','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Love','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Neutral','Like','Dislike','Like','Like');",
    "INSERT INTO [cooltable] VALUES ('Sebastian','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Hate','Like','Like','Neutral','Like','Neutral','Like','Neutral','Like','Dislike','Dislike','Like','Like','Like','Hate','Hate','Neutral','Like','Dislike','Hate','Dislike','Like','Like','Like','Dislike','Dislike','Dislike','Like','Like','Hate','Dislike','Hate','Neutral','Like','Like','Like','Dislike','Hate','Like','Like','Like','Like','Like','Like','Like','Love','Like','Dislike','Like','Like','Hate','Neutral','Dislike','Neutral','Like','Dislike','Dislike','Neutral','Like','Dislike','Like','Hate','Hate','Neutral','Dislike','Dislike','Neutral','Neutral','Like','Dislike','Neutral','Like','Like','Hate','Neutral','Like','Dislike','Neutral','Dislike','Love','Neutral','Dislike','Like','Hate','Hate','Like','Like','Like','Like','Hate','Hate','Dislike','Like','Like','Like','Like','Like','Hate','Like','Neutral','Like','Like','Love','Dislike','Like','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Neutral','Love','Neutral','Hate','Hate','Hate','Dislike','Dislike','Like','Neutral','Like','Neutral','Neutral','Like','Neutral','Like','Neutral','Hate','Dislike','Dislike','Neutral','Like','Like','Dislike','Neutral','Neutral','Dislike','Like','Like','Like','Like','Neutral','Hate','Dislike','Like','Love','Dislike','Hate','Dislike','Hate','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Shane','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Love','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Dislike','Like','Like','Like','Dislike','Like','Like','Like','Dislike','Like','Dislike','Like','Like','Like','Like','Dislike','Dislike','Like','Like','Hate','Dislike','Like','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Like','Like','Dislike','Dislike','Love','Like','Dislike','Like','Like','Hate','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Like','Like','Like','Love','Hate','Like','Dislike','Like','Love','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Dislike','Hate','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Dislike','Dislike','Like','Like','Like','Dislike','Neutral','Like','Like','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Dislike','Hate','Dislike','Like','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Vincent','Dislike','Like','Like','Like','Like','Like','Like','Dislike','Like','Hate','Dislike','Like','Dislike','Like','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Like','Like','Like','Hate','Hate','Like','Hate','Dislike','Like','Dislike','Like','Love','Like','Like','Like','Dislike','Like','Like','Hate','Dislike','Dislike','Neutral','Like','Like','Like','Like','Dislike','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Love','Like','Hate','Neutral','Dislike','Love','Hate','Dislike','Dislike','Dislike','Like','Dislike','Like','Like','Hate','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Like','Like','Hate','Dislike','Like','Dislike','Neutral','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Hate','Like','Like','Like','Like','Hate','Hate','Dislike','Love','Like','Like','Like','Like','Hate','Like','Dislike','Dislike','Dislike','Like','Dislike','Dislike','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Love','Dislike','Dislike','Like','Dislike','Like','Dislike','Neutral','Like','c','Like','Dislike','Hate','Like','Like','Dislike','Like','Like','Like','Neutral','Dislike','Dislike','Like','Like','Like','Like','Neutral','Hate','Like','Like','Dislike','Dislike','Hate','Hate','Hate','Dislike','Neutral','Dislike');",
    "INSERT INTO [cooltable] VALUES ('Willy','Like','Like','Like','Dislike','Dislike','Like','Dislike','Dislike','Dislike','Like','Like','Dislike','Neutral','Dislike','Neutral','Like','Love','Like','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Like','Neutral','Like','Dislike','Dislike','Dislike','Like','Dislike','Like','Like','Dislike','Dislike','Love','Neutral','Hate','Dislike','Neutral','Neutral','Dislike','Like','Dislike','Like','Like','Dislike','Like','Like','Dislike','Like','Like','Dislike','Like','Dislike','Dislike','Dislike','Dislike','Like','Neutral','Like','Neutral','Like','Dislike','Dislike','Neutral','Dislike','Love','Like','Like','Hate','Neutral','Dislike','Dislike','Like','Neutral','Like','Dislike','Neutral','Dislike','Dislike','Love','Neutral','Dislike','Dislike','Neutral','Dislike','Dislike','Love','Dislike','Like','Neutral','Like','Dislike','Dislike','Like','Dislike','Like','Like','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Hate','Dislike','Neutral','Love','Like','Dislike','Dislike','Like','Hate','Hate','Neutral','Dislike','Dislike','Dislike','Dislike','Dislike','Like','Dislike','Like','Neutral','Neutral','Love','Hate','Like','Hate','Dislike','Dislike','Dislike','Neutral','Dislike','Like','Neutral','Dislike','Neutral','Dislike','Love','Hate','Like','Like','Neutral','Dislike','Dislike','Like','Neutral','Like','Dislike','Dislike','Like','Dislike','Like','Neutral','Like','Like','Dislike','Dislike','Dislike','Hate','Dislike','Like','Dislike','Neutral','Like');",
    "INSERT INTO [cooltable] VALUES ('Wizard','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Neutral','Like','Neutral','Like','Dislike','Like','Dislike','Dislike','Like','Like','Like','Dislike','Like','Neutral','Like','Dislike','Like','Dislike','Like','Like','Like','Like','Dislike','Dislike','Like','Like','Hate','Dislike','Dislike','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Dislike','Dislike','Neutral','Like','Dislike','Dislike','Neutral','Like','Dislike','Like','Like','Hate','Dislike','Dislike','Like','Dislike','Dislike','Like','Dislike','Neutral','Like','Like','Like','Neutral','Like','Dislike','Neutral','Dislike','Like','Dislike','Dislike','Like','Dislike','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Like','Like','Like','Like','Hate','Like','Dislike','Like','Like','Like','Love','Like','Hate','Hate','Neutral','Like','Like','Like','Like','Like','Like','Like','Like','Dislike','Like','Dislike','Hate','Hate','Hate','Dislike','Love','Like','Neutral','Like','Dislike','Neutral','Like','Neutral','Like','Dislike','Hate','Like','Like','Love','Like','Like','Like','Neutral','Dislike','Like','Like','Like','Like','Like','Neutral','Like','Like','Like','Dislike','Love','Hate','Dislike','Like','Dislike','Neutral','Like');"]
    cursor_obj.execute(table)
    connection_obj.commit()
    for i in insert:
        cursor_obj.execute(i)
        connection_obj.commit()
    table = '''CREATE TABLE [fish] (
  [Stardew ValleyFish Guide (1.6.7)] TEXT,
  [Base Price] INT,
  [Price] INT,
  [] INT,
  [_2] INT,
  [_3] INT,
  [Spring] TEXT,
  [Summer] TEXT,
  [Fall] TEXT,
  [Winter] TEXT,
  [Weather] TEXT,
  [Location] TEXT,
  [Time] TEXT,
  [Difficulty] TEXT,
  [Bundle] TEXT,
  [Caught?] INT
);'''

    insert='''INSERT INTO [fish] ([Stardew ValleyFish Guide (1.6.7)],[Base Price],[Price],[],[_2],[_3],[Spring],[Summer],[Fall],[Winter],[Weather],[Location],[Time],[Difficulty],[Bundle],[Caught?])
VALUES
('Albacore',75,75,93,112,150,'No','No','Yes','Yes','Any','Ocean','6 AM - 11 AM
6 PM - 2 AM','Hard','No',FALSE),
('Anchovy',30,30,37,45,60,'Yes','No','Yes','No','Any','Ocean','Anytime','Easy','No',FALSE),
('Angler',900,900,1125,1350,1800,'No','No','Yes','No','Any','River','Anytime','Very hard','No',FALSE),
('Blob Fish',500,500,625,750,1000,'No','No','No','Yes','Any','Night Market','5 PM - 2 AM','Hard','No',FALSE),
('Blue Discus',120,120,150,180,240,'Yes','Yes','Yes','Yes','Any','Ginger Island','Anytime','Medium','No',FALSE),
('Bream',45,45,56,67,90,'Yes','Yes','Yes','Yes','Any','River','6 PM - 2 AM','Easy','Night Fishing Bundle',FALSE),
('Bullhead',75,75,93,112,150,'Yes','Yes','Yes','Yes','Any','Mountain Lake','Anytime','Medium','Lake Fish Bundle',FALSE),
('Carp',30,30,37,45,60,'Yes','Yes','Yes','Yes','Any','Mountain Lake, Secret Woods','Anytime','Very Easy','Lake Fish Bundle',FALSE),
('Catfish',200,200,250,300,400,'Yes','Yes, only in the Secret Woods','Yes','Yes, only with a Rain Totem','Rainy','Secret Woods, River, Witch''s Swamp','Anytime','Very Hard','River Fish Bundle',FALSE),
('Chub',50,50,62,75,100,'Yes','Yes','Yes','Yes','Any','Mountain Lake, River','Anytime','Easy','Field Research Bundle',FALSE),
('Crimsonfish',1500,1500,1875,2250,3000,'No','Yes','No','No','Any','Ocean','Anytime','Extreme','No',FALSE),
('Dorado',100,100,125,150,200,'No','Yes','No','No','Any','River','6 AM - 7 PM','Very Hard','No',FALSE),
('Eel',85,85,106,127,170,'Yes','No','Yes','No','Rainy','Ocean','4 PM - 2 AM','Hard','Night Fishing Bundle',FALSE),
('Flounder',100,100,125,150,200,'Yes','Yes','No','No','Any','Ocean','6 AM - 8 PM','Medium','No',FALSE),
('Ghostfish',45,45,56,67,90,'Yes','Yes','Yes','Yes','Any','Mines','Anytime','Medium','Specialty Fish Bundle',FALSE),
('Glacierfish',1000,1000,1250,1500,2000,'No','No','No','Yes','Any','River','6 AM - 11 PM','Extreme','No',FALSE),
('Gobi',150,150,187,225,300,'Yes','Yes','Yes','Yes','Any','Waterfalls','Anytime','Medium','No',FALSE),
('Halibut',80,80,100,120,160,'Yes','Yes','No','Yes','Any','Ocean','Anytime','Medium','No',FALSE),
('Herring',30,30,37,45,60,'Yes','No','No','Yes','Any','Ocean','Anytime','Very Easy','No',FALSE),
('Ice Pip',500,500,625,750,1000,'Yes','Yes','Yes','Yes','Any','Mines','Anytime','Very Hard','No',FALSE),
('Largemouth Bass',100,100,125,150,200,'Yes','Yes','Yes','Yes','Any','Mountain Lake','6 AM - 7 PM','Medium','Lake Fish Bundle',FALSE),
('Lava Eel',700,700,875,1050,1400,'Yes','Yes','Yes','Yes','Any','Mines','Anytime','Extreme','No',FALSE),
('Legend',5000,5000,6250,7500,10000,'Yes','No','No','No','Rainy','Mountain Lake','6 AM - 11 PM','Extreme','No',FALSE),
('Lingcod',120,120,150,180,240,'No','No','No','Yes','Any','Mountain Lake, River','Anytime','Very Hard','No',FALSE),
('Lionfish',100,100,125,150,200,'Yes','Yes','Yes','Yes','Any','Ginger Island','Anytime','Medium','No',FALSE),
('Midnight Carp',150,150,187,225,300,'No','No','Yes','Yes','Any','Mountain Lake, Forest Pond, Ginger Island North & West (freshwater)','10 PM - 2 AM','Medium','No',FALSE),
('Midnight Squid',100,100,125,150,200,'No','No','No','Yes','Any','Night Market','5 PM - 2 AM','Medium','No',FALSE),
('Mutant Carp',1000,1000,1250,1500,2000,'Yes','Yes','Yes','Yes','Any','Sewers','Anytime','Hard','No',FALSE),
('Octopus',150,150,187,225,300,'No','Yes','No','No','Any','Ocean','6 AM - 1 PM','Extreme','No',FALSE),
('Perch',55,55,68,82,110,'No','No','No','Yes','Any','Mountain Lake, River','Anytime','Easy','No',FALSE),
('Pike',100,100,125,150,200,'No','Yes','No','Yes','Any','River','Anytime','Hard','No',FALSE),
('Pufferfish',200,200,250,300,400,'No','Yes','No','No','Sunny','Ocean','12 PM - 4 PM','Hard','Specialty Fish Bundle',FALSE),
('Rainbow Trout',65,65,81,97,130,'No','Yes','No','No','Sunny','Mountain Lake, River','6 AM - 7 PM','Medium','No',FALSE),
('Red Mullet',75,75,93,112,150,'No','Yes','No','Yes','Any','Ocean','6 AM - 7 PM','Medium','No',FALSE),
('Red Snapper',50,50,62,75,100,'No','Yes','Yes','No','Rainy','Ocean','6 AM - 7 PM','Easy','Ocean Fish Bundle',FALSE),
('Salmon',75,75,93,112,150,'No','No','Yes','Yes','Any','River','6 AM - 7 PM','Medium','No',FALSE),
('Sandfish',75,75,93,112,150,'Yes','Yes','Yes','Yes','Any','Desert','6 AM - 8 PM','Hard','Specialty Fish Bundle',FALSE),
('Sardine',40,40,50,60,80,'Yes','No','Yes','Yes','Any','Ocean','6 AM - 7 PM','Easy','Ocean Fish Bundle',FALSE),
('Scorpion Carp',150,150,187,225,300,'Yes','Yes','Yes','Yes','Any','Desert','6 AM - 8 PM','Extreme','No',FALSE),
('Sea Cucumber',75,75,93,112,150,'No','No','Yes','Yes','Any','Ocean','6 AM - 7 PM','Easy','No',FALSE),
('Shad',60,60,75,90,120,'Yes','Yes','Yes','No','Rainy','River','9 AM - 2 AM','Medium','River Fish Bundle',FALSE),
('Slimejack',100,100,125,150,200,'Yes','Yes','Yes','No','Any','Mutant Bug Lair','Anytime','Medium','No',FALSE),
('Smallmouth Bass',50,50,62,75,100,'Yes','No','Yes','No','Any','Town River, Forest Pond','Anytime','Very Easy','No',FALSE),
('Spook Fish',220,220,275,330,440,'No','No','No','Yes','Any','Night Market','5 PM - 2 AM','Hard','No',FALSE),
('Squid',80,80,100,120,160,'No','No','No','Yes','Any','Ocean','6 PM - 2 AM','Very Hard','No',FALSE),
('Stingray',180,180,225,270,360,'Yes','Yes','Yes','Yes','Any','Ginger Island','Anytime','Hard','No',FALSE),
('Stonefish',300,300,375,450,600,'Yes','Yes','Yes','Yes','Any','Mines','Anytime','Hard','No',FALSE),
('Sturgeon',200,200,250,300,400,'No','Yes','No','Yes','Any','Mountain Lake','6 AM - 7 PM','Very Hard','Lake Fish Bundle',FALSE),
('Sunfish',30,30,37,45,60,'Yes','Yes','No','No','Sunny','River','6 AM - 7 PM','Easy','River Fish Bundle',FALSE),
('Super Cucumber',250,250,312,375,500,'No','Yes','Yes','Yes, on Night Market only','Any','Ocean','6 PM - 2 AM','Very Hard','No',FALSE),
('Tiger Trout',150,150,187,225,300,'No','No','Yes','Yes','Any','River','6 AM - 7 PM','Hard','River Fish Bundle',FALSE),
('Tilapia',75,75,93,112,150,'No','Yes','Yes','No','Any','Ocean','6 AM - 2 PM','Medium','Ocean Fish Bundle',FALSE),
('Tuna',100,100,125,150,200,'No','Yes','No','Yes','Any','Ocean','6 AM - 2 PM','Hard','Ocean Fish Bundle',FALSE),
('Void Salmon',150,150,187,225,300,'Yes','Yes','Yes','Yes','Any','Witch''s Swamp','Anytime','Very Hard','No',FALSE),
('Walleye',105,105,131,157,210,'No','No','Yes','No','Rainy','Mountain Lake, River','12 PM - 2 AM','Medium','Night Fishing Bundle',FALSE),
('Woodskip',75,75,93,112,150,'Yes','Yes','Yes','Yes','Any','Secret Woods','Anytime','Medium','Specialty Fish Bundle',FALSE);'''
    cursor_obj.execute(table)
    connection_obj.commit()
    cursor_obj.execute(insert)
    connection_obj.commit()
    return cursor_obj, connection_obj

data()