name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Kill previous iteration
      run: |
        pkill main.py
    - name: Install dependencies
      run: |
        python3 -m venv env
        source env/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  run:

    runs-on: self-hosted

    steps:
    - name: Run bot
      run: |
        cp /home/adam/token.txt env/.env
        source env/bin/activate
        nohup python src/main.py main >> /home/adam/out.txt &
        
